### PR TITLE
MNT: bump version number in setup.py

### PR DESCRIPTION
**Pull request by tacaswell**
Otherwise a source install sorts as older than 1.17.0 from pypi.

### CODE REVIEW

**Comment by arigo** [comment]
Maybe call it 17.0.1dev0?  Otherwise we can't release any other 17.x.x without making it appear older than previous checkins to the 18.0.0dev0 source.

**Comment by tacaswell** [comment]
Done!

**Comment by arigo** [comment]
Some version numbers were not updated.  Please run `test_version` or look in the failures of the automated test runs.

**Comment by tacaswell** [comment]
`__init__.py`` had both a `__version__` (which I caught) and a `__version_info__` (which I did not).

Should be fixed now and the tests pass locally.

**Pull request merged**
