### PR TITLE
Support for complex types with MSVC, called _Fcomplex and _Dcomplex

### PR DESCRIPTION
**Pull request by arigo**

### CODE REVIEW

**Comment by chris-hld** [comment]
Fixes https://github.com/python-cffi/cffi/issues/56 for [my setup.](https://github.com/chris-hld/SAFpy/blob/master/safpy_build.py)

**Comment by mattip** [comment]
Should this be adapted as a PR to the PyPy backend as well?

**Comment by arigo** [comment]
@mattip Good point!  I think a minimal change would be to copy the 2 lines added to each of `commontypes.c` and `parse_c_type.c`.  PyPy uses these C files directly in `pypy/module/_cffi_backend/src/`.  I think that's all that is required.  Some of the tests can also be ported, though.  I can give it a try (which mostly means trying to use github to make a PR to a large project like PyPy over a not-always-fast Internet connection).

**Comment by mattip** [comment]
> I can give it a try

Thanks. I opened pypy/pypy#4890 to track the problem and marked it for the next release.

**Pull request merged**
